/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kelompok1b.warteg40.view.Home.Widget;

import com.kelompok1b.warteg40.controller.CartController;
import com.kelompok1b.warteg40.model.Item;

/**
 *
 * @author akhda
 */
public class CartItemPanel extends javax.swing.JPanel {
    private final Item item;
    private final CartController cartController;
    /**
     * Creates new form CartItemPanel
     * @param newItem
     */
    public CartItemPanel(Item newItem, CartController controller) {
        initComponents();
        this.item = newItem;
        this.cartController = controller;
        label_nama.setText(item.getItemName());
        label_kategori.setText(String.valueOf(item.getCategory()));
        label_harga.setText(String.valueOf(item.getPrice()));
        label_qty.setText("x " + String.valueOf(item.getQty()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_nama = new javax.swing.JLabel();
        label_kategori = new javax.swing.JLabel();
        label_harga = new javax.swing.JLabel();
        label_qty = new javax.swing.JLabel();
        btn_min = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        label_nama.setText("Nama");
        jPanel1.add(label_nama);

        label_kategori.setText("Kategori");
        jPanel1.add(label_kategori);

        add(jPanel1);

        label_harga.setText("Harga");
        add(label_harga);

        label_qty.setText("Qty");
        add(label_qty);

        btn_min.setText("-");
        btn_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minActionPerformed(evt);
            }
        });
        add(btn_min);

        btn_plus.setText("+");
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });
        add(btn_plus);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        cartController.addToCart(item);
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btn_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minActionPerformed
        cartController.minItem(item);
    }//GEN-LAST:event_btn_minActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_min;
    private javax.swing.JButton btn_plus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_harga;
    private javax.swing.JLabel label_kategori;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_qty;
    // End of variables declaration//GEN-END:variables
}
