/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kelompok1b.warteg40.view.Home.Widget;

import com.kelompok1b.warteg40.controller.CartController;
import com.kelompok1b.warteg40.model.Item;

/**
 *
 * @author akhda
 */
public class GridMenu extends javax.swing.JPanel {
    private Item item;
    CartController cartController;

    /**
     * Creates new form GridMenu
     * @param newItem
     */
    public GridMenu(Item newItem, CartController cartController) {
        initComponents();
        this.cartController = cartController;
        this.item = newItem;
        label_nama.setText(item.getItemName());
        label_kategori.setText(item.getNameCategory());
        label_harga.setText(String.valueOf(item.getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_kategori = new javax.swing.JLabel();
        label_harga = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(120, 80));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        label_nama.setText("Nama");
        add(label_nama);

        label_kategori.setText("Kategori");
        add(label_kategori);

        label_harga.setText("Harga");
        add(label_harga);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        cartController.addToCart(item);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_harga;
    private javax.swing.JLabel label_kategori;
    private javax.swing.JLabel label_nama;
    // End of variables declaration//GEN-END:variables
}
