/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kelompok1b.warteg40.view.Home;

import com.kelompok1b.warteg40.controller.CartController;
import com.kelompok1b.warteg40.model.Item;
import java.awt.ComponentOrientation;
import java.awt.FlowLayout;
import java.awt.GridLayout;
//import com.kelompok1b.warteg40.view.Home.Widget.CartItemPanel;
import java.awt.Label;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Raihan Adam
 */
public class CartForm extends javax.swing.JFrame {
    CartController cartController;

    /**
     * Creates new form Checkout
     * @param cartController
     */
    public CartForm(CartController cartController) {
        initComponents();
        this.cartController = cartController;
        tampilCart();
    }
    
    public void tampilCart() {
        lbl_counter.setText(cartController.getCart().size() + " item");
        cart_panel.removeAll();
        for (Item item : cartController.getCart()) {
            JPanel itemPanel = new JPanel();
            itemPanel.setLayout(new FlowLayout());
            
            JPanel itemDetail = new JPanel();
            itemDetail.setLayout(new GridLayout(2, 1));
            itemDetail.add(new Label(item.getItemName()));
            itemDetail.add(new Label(item.getNameCategory()));
            
            itemPanel.add(itemDetail);
            itemPanel.add(new Label(String.valueOf(item.getPrice())));
            itemPanel.add(new Label("x " + String.valueOf(item.getQty())));
            
            JButton buttonPlus = new JButton();
            buttonPlus.setText("+");
            JButton buttonMin = new JButton();
            buttonMin.setText("-");
            buttonPlus.addActionListener((var e) -> {
                cartController.addToCart(item);
                tampilCart();
            });
            buttonMin.addActionListener((var e) -> {
                cartController.minItem(item);
                tampilCart();
            });
            
            itemPanel.add(buttonPlus);
            itemPanel.add(buttonMin);
            
            cart_panel.add(itemPanel);
//            cart_panel.add(new CartItemPanel(item, cartController));
        }
        cart_panel.repaint();
        cart_panel.revalidate();
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_counter = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scroll_cart = new javax.swing.JScrollPane();
        cart_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_checkout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 43));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Keranjang");
        jPanel2.add(jLabel1);

        jPanel4.setPreferredSize(new java.awt.Dimension(340, 12));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        lbl_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_counter.setText("jLabel2");
        jPanel2.add(lbl_counter);

        getContentPane().add(jPanel2);

        jPanel5.setPreferredSize(new java.awt.Dimension(339, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);

        cart_panel.setPreferredSize(new java.awt.Dimension(400, 350));
        cart_panel.setLayout(new javax.swing.BoxLayout(cart_panel, javax.swing.BoxLayout.PAGE_AXIS));
        scroll_cart.setViewportView(cart_panel);

        getContentPane().add(scroll_cart);

        jPanel3.setPreferredSize(new java.awt.Dimension(339, 12));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel1.setPreferredSize(new java.awt.Dimension(339, 20));
        jPanel1.setLayout(new java.awt.CardLayout());

        btn_checkout.setText("Checkout");
        btn_checkout.setPreferredSize(new java.awt.Dimension(77, 40));
        btn_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_checkout, "card2");

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkoutActionPerformed
        PaymentForm paymentForm = new PaymentForm(cartController);
        paymentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_checkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CartForm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checkout;
    private javax.swing.JPanel cart_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_counter;
    private javax.swing.JScrollPane scroll_cart;
    // End of variables declaration//GEN-END:variables
}
