/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kelompok1b.warteg40.view.Admin.widget;

import com.kelompok1b.warteg40.controller.CartController;
import com.kelompok1b.warteg40.controller.Searching;
import com.kelompok1b.warteg40.controller.TransactionController;
import com.kelompok1b.warteg40.model.Transaction;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akhda
 */
public class TransactionPanel extends javax.swing.JPanel {
    private CartController cartController;
    private TransactionController transactionController;
    private DefaultTableModel table_model = new DefaultTableModel();
    /**
     * Creates new form MenuPanel
     */
    public TransactionPanel() {
        initComponents();
        cartController = CartController.getInstance();
        transactionController = TransactionController.getInstance(cartController);
        
        table_model.addColumn("ID");
        table_model.addColumn("Nama");
        table_model.addColumn("Tanggal");
        table_model.addColumn("Jml Item");
        table_model.addColumn("Sub Total");
        table_model.addColumn("Bayar");
        table_model.addColumn("Kembalian");
        tampilData();
    }
    
    public void tampilData() {
        try {
             transactionController.getTransactions().forEach(transaction -> {
                 table_model.addRow(new Object[]{
                    transaction.getIdTransaction(),
                    transaction.getCustomerName(),
                    transaction.getDate(),
                    transaction.getCountOrderedItem(),
                    transaction.getSubTotal(),
                    transaction.getPaidMoney(),
                    transaction.getChangeMoney()
                });
             });
            table_transactions.setModel(table_model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data Transaksi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu1 = new java.awt.Panel();
        cmb_filter = new javax.swing.JComboBox<>();
        textfield_find = new javax.swing.JTextField();
        btn_find = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transactions = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        panel_menu1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        cmb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "id", "Nama", "SubTotal" }));
        cmb_filter.setMinimumSize(new java.awt.Dimension(120, 40));
        cmb_filter.setPreferredSize(new java.awt.Dimension(100, 40));
        cmb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_filterActionPerformed(evt);
            }
        });
        panel_menu1.add(cmb_filter);

        textfield_find.setText("Ketik yang Ingin Dicari");
        textfield_find.setMinimumSize(new java.awt.Dimension(240, 40));
        textfield_find.setPreferredSize(new java.awt.Dimension(240, 40));
        panel_menu1.add(textfield_find);

        btn_find.setText("Cari");
        btn_find.setMaximumSize(new java.awt.Dimension(80, 40));
        btn_find.setMinimumSize(new java.awt.Dimension(80, 40));
        btn_find.setPreferredSize(new java.awt.Dimension(80, 40));
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        panel_menu1.add(btn_find);

        add(panel_menu1);
        add(jPanel1);

        table_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Tanggal", "Bayar", "Kembalian", "Jml Pesanan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_transactions);
        if (table_transactions.getColumnModel().getColumnCount() > 0) {
            table_transactions.getColumnModel().getColumn(0).setHeaderValue("ID");
            table_transactions.getColumnModel().getColumn(1).setHeaderValue("Nama");
            table_transactions.getColumnModel().getColumn(2).setHeaderValue("Tanggal");
            table_transactions.getColumnModel().getColumn(3).setHeaderValue("Bayar");
            table_transactions.getColumnModel().getColumn(4).setHeaderValue("Kembalian");
            table_transactions.getColumnModel().getColumn(5).setHeaderValue("Jml Pesanan");
        }

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_filterActionPerformed
        int type = cmb_filter.getSelectedIndex();
        table_model.setRowCount(0);
        transactionController.sortTransaction(type);
        table_transactions.repaint();
        table_model.fireTableDataChanged();
        tampilData();
    }//GEN-LAST:event_cmb_filterActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        if (btn_find.getText().equals("Clear")) {
            btn_find.setText("Cari");
            textfield_find.setText(null);
            table_model.setRowCount(0);
            tampilData();
        } else {
            Searching search = new Searching();
            String keyword = textfield_find.getText();
            Transaction found = search.cariTransaksi(keyword, transactionController.getTransactions());
            if (found != null) {
                btn_find.setText("Clear");
                table_model.setRowCount(0);
                table_model.addRow(new Object[] {
                    found.getIdTransaction(),
                    found.getCustomerName(),
                    found.getDate(),
                    found.getCountOrderedItem(),
                    found.getSubTotal(),
                    found.getPaidMoney(),
                    found.getChangeMoney()
                });
                table_transactions.repaint();
                table_model.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(this, "Tidak Ditemukan");
            }
        }
    }//GEN-LAST:event_btn_findActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_find;
    private javax.swing.JComboBox<String> cmb_filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel_menu1;
    private javax.swing.JTable table_transactions;
    private javax.swing.JTextField textfield_find;
    // End of variables declaration//GEN-END:variables
}
